# Generated by Django 5.1.1 on 2024-12-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='charge_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
