# Generated by Django 5.1.1 on 2024-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_doctor_charge_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Monday - Friday', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(default='17:00:00'),
        ),
    ]
